# Generated by Django 3.2.3 on 2021-06-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Department', models.CharField(default='', max_length=100)),
                ('Salary', models.IntegerField(max_length=100)),
            ],
        ),
    ]
