# Generated by Django 3.2.4 on 2021-06-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='employee_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='Department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Salary',
            field=models.IntegerField(),
        ),
    ]
