# Generated by Django 3.2.3 on 2021-06-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0005_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='default.jpg', upload_to='product_image/'),
        ),
    ]
