# Generated by Django 3.2.4 on 2021-06-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='talkModel',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Speaker', models.CharField(max_length=100)),
                ('Venue', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
